In [1]:
%pip install tensorflow


Note: you may need to restart the kernel to use updated packages.


In [4]:
import tensorflow as tf 


In [5]:
a = tf.constant([[1,2],[3,4]])
print(a)
print(a.shape)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
(2, 2)


In [6]:
import tensorflow as tf
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
result = a + b  
print(result)  

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [7]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(a, b)
print(result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [8]:
import torch

# 1. Create tensor
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# 2. Element-wise
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
print(a + b)           # addition

# 3. Matrix multiplication
print(torch.matmul(a, b))

# 4. Activation (ReLU)
print(torch.relu(a - 3))

# 5. Reshape
print(a.reshape(4))

# 6. Sum
print(torch.sum(a))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[19., 22.],
        [43., 50.]])
tensor([[0., 0.],
        [0., 1.]])
tensor([1., 2., 3., 4.])
tensor(10.)
