In [1]:
import torch
import torch.nn as nn
import tensorflow as tf


In [ ]:
relu = nn.ReLU()
X = torch.tensor([-1.0, 0.0, 1.0])
print(relu(x))

tensor([0., 0., 1.])


In [8]:
#appying Sigmoid Function 
sigmoid = nn.Sigmoid()
print(sigmoid(x))

tensor([0.2689, 0.5000, 0.7311])


In [ ]:
#now via TensorFlow
array2 = tf.constant([-1.0,1.0,1.5,0.5])
a=tf.nn.relu(array2)
print(a)




tf.Tensor([0.  1.  1.5 0.5], shape=(4,), dtype=float32)


In [17]:
#now implementing Tanh via Tensors and torch 
x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
x1 = tf.constant([-2.0, -1.0, 0.0, 1.0, 2.0])


In [18]:
print(torch.tanh(x))
print(tf.tanh(x1))

tensor([-0.9640, -0.7616,  0.0000,  0.7616,  0.9640])
tf.Tensor([-0.9640276 -0.7615942  0.         0.7615942  0.9640276], shape=(5,), dtype=float32)


In [ ]:
#implementation of softMax Activation Functions
