In [6]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.datasets import load_iris

In [7]:
iris = load_iris()
X=iris.data
y=iris.target

In [8]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,random_state=42,test_size=0.3)


In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
class IrisDataset(Dataset): #Defining a class , also taking Dataset which means we are inheriting from the torch.utils.Datset from PyTorch ,
    #this means That we can now use the basic Functionality of the Torch Datsset and we can customize how this can be accessed 
    def __init__ (self,features,labels): # defing a constructor , gets called automatically 
        #self refers to the Current object/Instance Being Created 
        #features and labels Ykwim 
         
        self.X = torch.tensor(features, dtype=torch.float32) # turns your Feature Data into Tensors that torch can read 
        self.y = torch.tensor(labels, dtype=torch.long) #torch.tensor here also meant the same and means this will be converted to Long Format 
#splitting of Dataset , for features and target variables  
        
        
def __len__(self):
    return len(self.x) # finds the length of the Samples in the dataset (finds out how many are there) 
#if self.X has 150 rows then , it will return 150

def __getitem__(self, idx):  #tells python how to get an item , given its position and index
    #if the datsset[5] => idx = 5. 
    
    return self.X[idx], self.y[idx] # returns the data ( features and Labels) for the sample Position at idx 
# this method is used in pytorch to get batches of data during training.
    
        

In [13]:
dataset = IrisDataset(X,y)

In [14]:
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
loader = DataLoader(dataset, batch_size=16, shuffle=True)
#for batching , optional